name: Ubuntu VPS
on: workflow_dispatch
jobs:
  web_app_defn:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      juice_shop_app:
        image: bkimminich/juice-shop
        ports:
          - 80:80
          - 443:443
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run container
      run: |
        echo "Loading..."
        sudo echo "adduser --gecos "" --disabled-password runner --force-badname"
        sudo echo "usermod -aG sudo runner"
        echo "runner:LotusOS" | sudo chpasswd
        echo "root:LotusOS" | sudo chpasswd
        sudo apt-get update
        sudo apt-get install nano htop -y
        git config --global user.name "dopaemon"
        git config --global user.email "polarisdp@gmail.com"
        git config --global core.editor "nano"
    - uses: KernelPanic-OpenSource/LinuxSSH@v1.5.2
      with:
        timeout: 6h
        port: 22
        ngrok_authtoken: 1zduK1GhoyyWPe6hHsJlhR1gG9R_5TNjK9mjiKXhTaC3bBSyc
        
