name: Ubuntu VPS
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
      with:
        timeout: 6h
        port: 2222
        ngrok_authtoken: 1zduK1GhoyyWPe6hHsJlhR1gG9R_5TNjK9mjiKXhTaC3bBSyc
