name: Ubuntu VPS
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: adduser --gecos "" --disabled-password doraemon --force-badname
    - run: chpasswd <<<"doraemon:123456"
    - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
      with:
        timeout: 6h
        port: 22
        ngrok_authtoken: 1zduK1GhoyyWPe6hHsJlhR1gG9R_5TNjK9mjiKXhTaC3bBSyc
    - run: echo ""
    - run: echo "=========================================="
    - run: echo "To connect: $(grep -o -E "tcp://(.+)" < .ngrok.log | sed "s/tcp:\/\//ssh $USER@/" | sed "s/:/ -p /")"
    - run: echo "=========================================="
