name: Ubuntu VPS
on: workflow_dispatch
jobs:
  Container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run container
      run: |
        echo "Loading..."
        sudo echo "adduser --gecos "" --disabled-password runner --force-badname"
        sudo echo "usermod -aG sudo runner"
        echo "runner:LotusOS" | sudo chpasswd
        echo "root:LotusOS" | sudo chpasswd
    - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
      with:
        timeout: 6h
        port: 22
        ngrok_authtoken: 1zduK1GhoyyWPe6hHsJlhR1gG9R_5TNjK9mjiKXhTaC3bBSyc
        
